# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

In this lecture, we will go through the range of important NumPy's concepts and built-in function that we will be frequently using in the coming sections. As usual, this notebook is a reference to the video lecture. You can always explore this notebook if you need help.  

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype` 
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [1]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [2]:
# Lets create a Python list. 
my_list = [-1,0,1]
my_list
my_list[0]

-1

In [3]:
type(my_list)

list

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [4]:
my_array = np.array(my_list) 
my_array
my_array[0]

-1

In [5]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6],[7,8,9],[4, 5, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [6]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [7]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [8]:
np.arange(0,10) # similar to range() in Python, not including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# We can give the step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [11]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 15, 15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [12]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [13]:
np.linspace(0,15,30) # 1-D array 

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

### `zeros()`

* We want to create an array with **all zeros**<br>

*Press shift+tab for the documentation.*

In [14]:
np.zeros(15) # 1-D with 3 elements

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((4,6)) #(no_row, no_col) passing a tuple

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### `ones()`

* We want to create an array with **all ones**<br>

*Press shift+tab for the documentation.*

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((4,6)) #(no_row, no_col) passing a tuple

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## `eye()` 
Creates an identity matrix must be a square matrix, which is useful in several linear algebra problems.
* Return a 2-D array with **ones on the diagonal and zeros elsewhere.**

*Press shift+tab for the documentation.*

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [19]:
np.random.rand(3) # 1-D array with three elements

array([0.10267073, 0.19107113, 0.57826637])

In [20]:
np.random.rand(3,2) # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.53980376, 0.93065065],
       [0.40554407, 0.9568355 ],
       [0.27525252, 0.36064925]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [21]:
np.random.randn(5)

array([-2.65919769,  1.30845008,  0.3293168 ,  1.54534932,  1.62382265])

In [22]:
np.random.randn(100,100) # no tuple, each dimension as a separate argument

array([[-0.01804337, -2.08107875,  2.0636987 , ..., -0.60151109,
         0.11439781, -0.06794506],
       [ 0.60124462, -0.72389875, -0.92528172, ..., -1.89483514,
         2.35630037,  0.65314192],
       [-0.33235906,  0.06568494, -1.34892198, ..., -0.92390417,
         0.30573101,  0.66239123],
       ...,
       [ 0.62758963, -0.67360282,  0.27151473, ...,  0.20125738,
         0.94066947, -2.13299344],
       [ 1.61637744,  1.91053309, -0.60426911, ..., -0.49261574,
         0.83125454,  0.32255746],
       [ 1.06270081,  0.0709451 , -0.02091145, ...,  1.79221597,
        -1.15934141, -0.75431186]])

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1,100) #returns one random int, 1 inclusive, 100 exclusive

32

In [24]:
np.random.randint(1,500,10) #returns ten random int,

array([206, 446, 299, 413, 162, 356, 173,  67, 219, 333])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [25]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_ranint = np.random.randint(0,100,10)

In [26]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
array_ranint

array([85, 27, 15, 88, 60, 12,  0, 53, 35, 97])

#### `Reshape()`
Returns an array containing the same data with a new shape.

In [28]:
reshape_test=array_arange.reshape(4,4) # any other num will give error
reshape_test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [29]:
array_ranint

array([85, 27, 15, 88, 60, 12,  0, 53, 35, 97])

In [30]:
array_ranint.max()

97

In [31]:
array_ranint.min()

0

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [32]:
array_ranint.argmax() # index starts from 0

9

In [33]:
array_ranint.argmin()

6

### Attributes
* `size, shape, dtype` 

In [34]:
# Lets take vector array, array_arange 
array_arange.shape
#reshape_test.shape

(16,)

In [35]:
# Size of the array 
array_arange.size

16

In [36]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [37]:
# Notice the two sets of brackets
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
array_arange.reshape(4,4).shape

(4, 4)

In [39]:
array_arange.reshape(16,1).shape

(16, 1)

In [40]:
array_arange.reshape(1,16).shape

(1, 16)

### Indexing & slicing of 1-D arrays (vectors)

In [41]:
# Lets create a simple 1-D NumPy array.
# (we can use arange() as well.) 
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [42]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [43]:
# Getting value at certain index
array_1d[0]

-10

In [44]:
# Getting a range value
array_1d[0:3], array_1d
# array_1d is included in the out to compare and understand

(array([-10,  -2,   0]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [45]:
# Using -ve index 
array_1d[-2], array_1d
# array_1d is included in the out to compare and understand

(106, array([-10,  -2,   0,   2,  17, 106, 200]))

In [46]:
# Using -ve index for a range 
array_1d[1:-2], array_1d # 1 inclusive and -2 exclusive in this case

(array([-2,  0,  2, 17]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [47]:
# Getting up-to and from certain index -- remember index starts from '0'
# (no need to give start and stop indexes)
array_1d[:2], array_1d[2:]

(array([-10,  -2]), array([  0,   2,  17, 106, 200]))

In [48]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [49]:
array_1d
# The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [50]:
array_2d= np.arange(24)
array_2d.shape = (6,4) #array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [51]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [52]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [53]:
# To get an individual element value at row = 5 and column = 2
array_2d[5,2]

22

In [54]:
# another way 
row = 5
column = 2
array_2d[row, column]

22

In [55]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

22

In [56]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
# 2D array slicing
array_2d[:2,:2] # array_2d[:2,:2].shape gives (2,2), 4 elements for top left corner 
#[row:row, column:column] [From 0 row to 1 row, From 0 column to 1 column]
# array_2d[0:2,0:2] is same as array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [58]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [59]:
array_1d[0:5] = 500 
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [60]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [62]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [63]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [64]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [65]:
array_2d[[1, 2, 3]]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
# We can use any order
array_2d[[3,0,1]]

array([[  1.,   1.,   1.,   1.],
       [300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.]])

In [67]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
# grabbing rows
array_2d[[2,4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [69]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

In [70]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can apply condition such as >, <, == etc

In [71]:
array_1d > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [72]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

Lets create a mask to **filter out the even numbers in "array_1d"**

In [73]:
array_1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [74]:
0 == array_1d % 2

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [75]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = 0 == array_1d % 2 
mod_2_mask_1d

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [76]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

array([ 2,  4,  6,  8, 10])

## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>
 

## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [77]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

array([0, 1, 2, 3, 4])

In [78]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

In [79]:
# Subtracting two arrays
arr - arr

array([0, 0, 0, 0, 0])

In [80]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16])

In [81]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

C:\Users\Minhazul Kabir\AppData\Local\Temp\ipykernel_7580\1371265232.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.])

In [82]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

C:\Users\Minhazul Kabir\AppData\Local\Temp\ipykernel_7580\1491116826.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr #[0, 1, 2, 3, 4]


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [83]:
# Power of all the elements in an array
arr ** 2

array([ 0,  1,  4,  9, 16])

In [84]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [85]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [86]:
# max and min values
np.max(arr), np.min(arr)

(4, 0)

In [87]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [88]:
#18a:
# To avoid overwriting the output, please code here 

In [89]:
array_2d= np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [90]:
#18b:
# To avoid overwriting the output, please code here 

In [91]:
array_2d[3:, 2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [92]:
#18c:
# To avoid overwriting the output, please code here 

In [93]:
array_2d[5,4] # array_2d[5][4]

29

In [94]:
#18d:
# To avoid overwriting the output, please code here 

In [95]:
array_2d[:3,1:2] # array_2d[:3,1:3] for col 1 and 2 

array([[ 1],
       [ 6],
       [11]])

In [96]:
#18e:
# To avoid overwriting the output, please code here 

In [97]:
array_2d[2,:] # array_2d[2:3,:] will give the same output

array([10, 11, 12, 13, 14])

In [98]:
#18f:
# To avoid overwriting the output, please code here 

In [99]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [100]:
array_2d[2:4,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Calculate the sum of all the numbers in array_2d?**

In [101]:
# To avoid overwriting the output, please code here 
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [102]:
array_2d.sum()

435

In [103]:
array_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

**Calculate sum of all the rows and columns in array_2d.**

In [104]:
# To avoid overwriting the output, please code here 

In [105]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

Row sum: [ 10  35  60  85 110 135]
Columns sum: [75 81 87 93 99]


**Calculate the standard deviation of the values in array_2d.**

In [106]:
# To avoid overwriting the output, please code here 

In [107]:
array_2d.std()

8.65544144839919

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [108]:
# To avoid overwriting the output, please code here 

In [109]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [110]:
array_2d % 3 != 0

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [111]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [112]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])

In [113]:
array_2d[2:4,2:4] # inner slice [From 2 row to 3 row, From 2 column to 3 column]

array([[12, 13],
       [17, 18]])